// AWS Academy Cloud Foundations: Module Knowledge Checks (извлечено из курса, ответы официальные)
// Формат вопроса: [текст, [варианты], [индексы правильных], пояснение]
window.KC_SETS = [
{ id: "m1", code: "M01", title: "Cloud Concepts Overview", ru: "Основы облака", qs: [
["What are the advantages of cloud computing over computing on-premises? (Select the best answer.)",["Avoid large capital purchases","Use on-demand capacity","Go global in minutes","Increase speed and agility","All of the above"],[4],"With cloud computing, all of these are possible."],
["What is the pricing model that enables AWS customers to pay for resources on an as-needed basis? (Select the best answer.)",["Pay as you decommission","Pay as you go","Pay as you buy","Pay as you reserve"],[1],"With AWS, you pay for resources as you go."],
["Which of these is NOT a cloud computing model? (Select the best answer.)",["Platform as a service","Infrastructure as a service","System administration as a service","Software as a service"],[2],"System administration as a service is not a cloud computing model."],
["True or False? AWS owns and maintains the network-connected hardware required for application services, while you provision and use what you need.",["True","False"],[0],"It’s true that AWS owns and maintains the hardware, while you provision and use what you need."],
["Which of these is NOT a benefit of cloud computing over on-premises computing? (Select the best answer.)",["Increase speed and agility","Pay for racking, stacking, and powering servers","Eliminate guessing on your infrastructure capacity needs","Trade capital expense for variable expense","Benefit from massive economies of scale"],[1],"Paying for racking, stacking and powering servers is not a benefit of cloud computing over on-premises computing."],
["Which of the following are NOT benefits of AWS Cloud computing? (Choose two.)",["High latency","Multiple procurement cycles","Fault-tolerant databases","Temporary and disposable resources","High availability"],[0,1],"High latency and multiple procurement cycles are not benefits of AWS Cloud computing."],
["Which of the following is a compute service? (Select the best answer.)",["Amazon VPC","Amazon S3","Amazon EC2","Amazon CloudFront","Amazon Redshift"],[2],"Amazon EC2 is a compute service."],
["True or False? Cloud computing provides a simple way to access servers, storage, databases, and a broad set of application services over the internet. You own the network-connected hardware required for these services and Amazon Web Services provisions what you need.",["True","False"],[1],"One of the key benefits of cloud computing is the opportunity to replace upfront capital infrastructure expenses with low variable costs that scale with your business."],
["Economies of scale result from ______. (Select the best answer.)",["having many different cloud providers","having hundreds of thousands of customers aggregated in the cloud","having hundreds of cloud services available over the internet","having to invest heavily in data centers and servers"],[1],"Economies of scale results from having hundreds of thousands of customers aggregated in the cloud."],
["Which of these are ways to access AWS core services? (Choose three.)",["Software Development Kits (SDKs)","AWS Command Line Interface (AWS CLI)","AWS Management Console","AWS Marketplace","Technical support calls"],[0,1,2],"The three ways to access AWS core services are the AWS Management Console, the AWS Command Line Interface and Software Development Kits."]
]},
{ id: "m2", code: "M02", title: "Cloud Economics and Billing", ru: "Экономика и биллинг", qs: [
["For certain services like Amazon Elastic Compute Cloud (Amazon EC2) and Amazon Relational Database Service (Amazon RDS), you can invest in reserved capacity. What options are available for Reserved Instances? (Choose three.)",["PURI","NURI","AURI","DURI","MURI"],[0,1,2],"Reserved Instances are available in AURI, NURI, and PURI."],
["Where can a customer go to get more details about Amazon Elastic Compute Cloud (Amazon EC2) billing activity that took place 3 months ago? (Select the best answer.)",["Amazon EC2 dashboard","AWS Cost Explorer","AWS Trusted Advisor dashboard","AWS CloudTrail logs stored in Amazon Simple Storage Service (Amazon S3)"],[1],"AWS Cost Explorer can give you more details about Amazon EC2 billing activity for the past 3 months."],
["True or false? To receive the discounted rate associated with Reserved Instances, you must make a full, upfront payment for the term of the agreement. (Select the best answer.)",["True","False"],[1],"To receive the discounted rate associated with Reserved Instances, you do not need to make a full, upfront payment."],
["Which statement is true about the pricing model on AWS? (Select the best answer.)",["In most cases, there is a per gigabyte charge for inbound data transfer.","Storage is typically charged per gigabyte.","Compute is typically charged as a monthly fee based on instance type.","Outbound charges are free up to a per account limit."],[1],"Storage is typically charged based on how many gigabytes you use. For services that use tiered pricing, the per gigabyte cost is less when you use more."],
["What are the four support plans offered by AWS Support? (Select the best answer.)",["Basic, Developer, Business, Enterprise","Basic, Startup, Business, Enterprise","Free, Bronze, Silver, Gold","All support is free"],[0],"The four support plans offered by AWS Support are Basic, Developer, Business, and Enterprise."],
["What AWS tool lets you explore AWS services and create an estimate for the cost of your use cases on AWS? (Select the best answer.)",["AWS Pricing Calculator","AWS Budgets","AWS Cost and Usage Report","AWS Billing Dashboard"],[0],"The AWS Pricing Calculator lets you model your solutions before building them, explore the price points and calculations behind your estimate, and find the available instance types and contract terms that meet your needs."],
["As AWS grows, the cost of doing business is reduced and savings are passed back to the customer with lower pricing. What is this optimization called? (Select the best answer.)",["Expenditure awareness","Economies of scale","Matching supply and demand","EC2 Right Sizing"],[1],"As AWS grows, the general cost of doing business is reduced and savings are passed back to the customer due to economies of scale."],
["True or false? AWS offers some services at no charge, such as, Amazon Virtual Private Cloud, AWS Identity and Access Management, Consolidated Billing, AWS Elastic Beanstalk, automatic scaling, AWS OpsWorks and AWS CloudFormation. However, you might be charged for other AWS services that you use in conjunction with these services.",["True","False"],[0],"AWS offers these services at no charge, though you might be charged for other AWS services that you use in conjunction with these services."],
["What are benefits of using AWS Organizations? (Choose two.)",["Simplifies automating account creation and management by using APIs","Provides the ability to create groups of accounts and then attach policies to a group","Prevents any restrictions from being put on the root user that is associated with the main organization in an account","Provides the ability to create an unlimited number of nested organizational units (OUs) to support your desired structure","Replaces existing AWS Identity and Access Management (IAM) policies with service control policies (SCPs), which are simpler to manage"],[0,1],"With AWS Organizations, you can create groups of accounts and then attach policies to a group. You can use the API to automate account creation and management."],
["True or false? Unlimited services are available with the AWS Free Tier to new AWS customers for 12 months following their AWS sign-up date. (Select the best answer.)",["True","False"],[1],"The AWS Free Tier applies to certain services and options."]
]},
{ id: "m3", code: "M03", title: "AWS Global Infrastructure Overview", ru: "Глобальная инфраструктура", qs: [
["Which component of the AWS Global Infrastructure does Amazon CloudFront use to ensure low-latency delivery? (Select the best answer.)",["AWS Regions","AWS edge locations","AWS Availability Zones","Amazon Virtual Private Cloud (Amazon VPC)"],[1],"Amazon CloudFront uses AWS edge locations to ensure low-latency delivery."],
["You can run applications and workloads from a Region closer to the end users to _______ latency.",["increase","decrease"],[1],"You can run applications and workloads from a Region closer to the end users to decrease latency."],
["True or False? Networking, storage, compute, and databases are examples of service categories that AWS offers.",["True","False"],[0],"These are examples of service categories that AWS offers."],
["Which of the following are geographic areas that host two or more Availability Zones? (Select the best answer.)",["AWS Origins","AWS Regions","Compute zones","Edge locations"],[1],"AWS Regions host two or more Availability Zones."],
["______ means the infrastructure has built-in component redundancy and ______ means that resources dynamically adjust to increases or decreases in capacity requirements.",["No human intervention, fault tolerant","Elastic and scalable, no human intervention","Fault tolerant, elastic and scalable","Fault tolerant, no human intervention","Elastic and scalable, fault tolerant"],[2],"Fault tolerant means the infrastructure has built-in component redundancy and elastic and scalable means that resources dynamically adjust to increases or decreases in capacity requirements."],
["True or False? Availability Zones within a Region are connected through low-latency links.",["True","False"],[0],"It's true that Availability Zones within a Region are connected through low-latency links."],
["Which of these statements about Availability Zones is not true? (Select the best answer.)",["Availability Zones are designed for fault isolation.","Availability Zones are made up of one or more data centers.","A data center can be used for more than one Availability Zone.","Availability Zones are connected to each other using high-speed private links."],[2],"A data center cannot be used for more than one Availability Zone."],
["What is true about Regions? (Choose two.)",["A Region is a physical location that has multiple Availability Zones.","Each Region is located in a separate geographic area.","They are the physical locations of your customers.","All Regions are located in one specific geographic area."],[0,1],"Each Region is located in a separate geographic area and is a physical location that has multiple Availability Zones."],
["AWS highly recommends provisioning your compute resources across _______ Availability Zones. (Select the best answer.)",["no","multiple","single","all"],[1],"AWS highly recommends provisioning your compute resources across multiple Availability Zones."],
["True or False? Edge locations are only located in the same general area as Regions.",["True","False"],[1],"Edge locations do not need to be located in the same general area as Regions."]
]},
{ id: "m4", code: "M04", title: "AWS Cloud Security", ru: "Безопасность", qs: [
["In the shared responsibility model, AWS is responsible for providing what? (Select the best answer.)",["Security of the cloud","Security to the cloud","Security for the cloud","Security in the cloud"],[0],"In the shared responsibility model, AWS is responsible for providing security of the cloud."],
["In the shared responsibility model, which of the following are examples of \"security in the cloud\"? (Choose two.)",["Encryption of data at rest and data in transit","Security group configurations","Protecting the global infrastructure","Physical security of the facilities in which the services operate","Compliance with compute security standards and regulations"],[0,1],"Encryption of data at rest and data in transit and security group configurations are examples of security in the cloud."],
["Which of the following is the responsibility of AWS under the AWS shared responsibility model? (Select the best answer.)",["Configuring third-party applications","Maintaining physical hardware","Security application access and data","Managing custom Amazon Machine Images (AMIs)"],[1],"Maintaining physical hardware is the responsibility of AWS under the shared responsibility model."],
["When creating an AWS Identity and Access Management (IAM) policy, what are the two types of access that can be granted to a user? (Choose two.)",["AWS Management Console access","Programmatic access","Administrative root access","Authorized access","Institutional access"],[0,1],"When creating an IAM policy, a user can be granted AWS Management Console access and programmatic access."],
["True or False? AWS Organizations enables you to consolidate multiple AWS accounts so that you centrally manage them.",["True","False"],[0],"True. AWS Organizations enables you to consolidate multiple AWS accounts so that you centrally manage them."],
["Which of the following are best practices to secure your account using AWS Identity and Access Management (IAM)? (Choose two.)",["Define fine-grained access rights.","Manage access to AWS resources.","Avoid using IAM groups to grant the same access permissions to multiple users.","Leave unused and unnecessary users and credentials in place.","Provide users with default administrative privileges."],[0,1],"Managing access to AWS resources and defining fine-grained access rights are best practices when securing accounts with AWS IAM."],
["Which of the following should be done by the AWS account root user? (Select the best answer.)",["Secure access for applications","Integrate with other AWS services","Change granular permissions","Change the AWS support plan"],[3],"Changing the AWS support plan can only be done by the AWS account root user. The other tasks are done with IAM."],
["After initial login, what does AWS recommend as the best practice for the AWS account root user? (Select the best answer.)",["Delete the AWS account root user","Revoke all permissions on the AWS account root user","Restrict permission on the AWS account root user","Delete the access keys of the AWS account root user"],[3],"After initial login, AWS recommends deleting the access keys of the AWS account root user as the best practice."],
["How would a system administrator add an additional layer of login security to a user's AWS Management Console? (Select the best answer.)",["Use Amazon Cloud Directory","Audit AWS Identity and Access Management (IAM) roles","Enable multi-factor authentication","Enable AWS CloudTrail"],[2],"To add an additional layer of login security to a user's AWS Management Console, enable multi-factor authentication."],
["True or False? AWS Key Management Service (AWS KMS) enables you to assess, audit, and evaluate the configurations of your AWS resources.",["True","False"],[1],"AWS Key Management Service (AWS KMS) is a service that allows you to create and manage encryption keys and control the use of encryption across a wide range of AWS services and in your applications."]
]},
{ id: "m5", code: "M05", title: "Networking and Content Delivery", ru: "Сети и доставка контента", qs: [
["With Amazon Virtual Private Cloud (Amazon VPC), what is the smallest size subnet you can have in a VPC? (Select the best answer.)",["/24","/26","/28","/30"],[2],"The smallest size subnet you can have in a VPC is /28."],
["With Amazon Virtual Private Cloud (Amazon VPC), what is the maximum size IP address range you can have in a VPC? (Select the best answer.)",["/16","/24","/28","/30"],[0],"The maximum size IP address range you can have in a VPC is /16."],
["You need to allow resources in a private subnet to access the internet. Which of the following must be present to enable this access? (Select the best answer.)",["Security groups","NAT gateway","Route tables","Network access control lists"],[1],"If you need to allow resources in a private subnet to access the internet, a NAT gateway must be present to enable this access."],
["Which AWS networking service enables a company to create a virtual network within AWS? (Select the best answer.)",["AWS Config","Amazon Route 53","AWS Direct Connect","Amazon Virtual Private Cloud (Amazon VPC)"],[3],"Amazon Virtual Private Cloud enables a company to create a virtual network within AWS."],
["True or False? Private subnets have direct access to the internet.",["True","False"],[1],"Private subnets do not have direct access to the internet."],
["Which component of AWS Global Infrastructure does Amazon CloudFront use to ensure low-latency delivery? (Select the best answer.)",["AWS Regions","AWS Availability Zones","AWS edge locations","Amazon Virtual Private Cloud (Amazon VPC)"],[2],"To ensure low-latency delivery, Amazon CloudFront uses AWS edge locations."],
["Which of the following is an optional security control that can be applied at the subnet layer of a VPC? (Select the best answer.)",["Network ACL","Security group","Firewall","Web application firewall"],[0],"A network ACL is an optional security control that can be applied at the subnet layer of a VPC."],
["What happens when you use Amazon Virtual Private Cloud (Amazon VPC) to create a new VPC? (Select the best answer.)",["An internet gateway is created by default.","Three subnets are created by default in one Availability Zone.","A main route table is created by default.","Three subnets are created by default: one for each Availability Zone."],[2],"When you create a VPC, a route table is created by default. You must manually create subnets and an internet gateway."],
["Which of the following can be used to protect Amazon Elastic Compute Cloud (Amazon EC2) instances hosted in AWS? (Select the best answer.)",["Security group","AMI","Internet Gateway","All of the above"],[0],"A security group acts as a virtual firewall for your instance to control inbound and outbound traffic."],
["You are a solutions architect who works at a large retail company that is migrating its existing infrastructure to AWS. You recommend that they use a custom VPC. When you create a VPC, you assign it to an IPv4 Classless Inter-Domain Routing (CIDR) block of 10.0.1.0/24 (which has 256 total IP addresses). How many IP addresses are available? (Select the best answer.)",["246","251","250","256"],[1],"The subnet has 256 IP addresses but only 251 are available because 5 are reserved."]
]},
{ id: "m6", code: "M06", title: "Compute", ru: "Вычисления", qs: [
["Why is AWS more economical than traditional data centers for applications with varying compute workloads? (Select the best answer.)",["Amazon EC2 costs are billed on a monthly basis.","Customers retain full administrative access to their Amazon EC2 instances.","Customers can permanently run enough instances to handle peak workloads.","Amazon EC2 instances can be launched on-demand when needed."],[3],"AWS is more economical than traditional data centers with varying compute workloads because Amazon EC2 instances can be launched on-demand."],
["If your project requires monthly reports that iterate through very large amounts of data, which Amazon Elastic Compute Cloud (Amazon EC2) purchasing option should you consider? (Select the best answer.)",["Spot Instances","Scheduled Reserved Instances","Dedicated Hosts","On-Demand Instances"],[1],"If your project requires you to run monthly reports that iterate through very large amounts of data, you should consider purchasing Scheduled Reserved Instances."],
["What is included in an Amazon Machine Image (AMI)? (Select the best answer.)",["A template for the root volume for the instance","Launch permissions that control which AWS accounts can use the AMI to launch instances.","A block device mapping that specifies the volumes to attach to the instance when it's launched","All of the above"],[3],"An Amazon Machine Image (AMI) includes all of these."],
["Which Amazon Elastic Compute Cloud (Amazon EC2) feature ensures your instances will not share a physical host with instances from any other AWS customer? (Select the best answer.)",["Amazon VPC","Placement groups","Dedicated Instances","Reserved Instances"],[2],"Dedicated Instances ensure your instances will not share a physical host with instances from any other AWS customer."],
["Which of the following services is a serverless compute service in AWS? (Select the best answer.)",["AWS Config","AWS Lambda","AWS OpsWorks","Amazon EC2"],[1],"AWS Lambda is a compute service that lets you run code without provisioning or managing servers."],
["What is the service provided by AWS that enables developers to easily deploy and manage applications in the cloud? (Select the best answer.)",["Amazon Elastic Container Service","AWS Elastic Beanstalk","AWS OpsWorks","AWS CloudFormation"],[1],"Elastic Beanstalk is an AWS compute service option. It is a Platform as a Service (PaaS) that facilitates quick deployment, scaling and managing of your web applications and services."],
["Your web application needs four instances to support steady traffic all of the time. On the last day of the month, the traffic triples. What is the most cost-effective way to handle this pattern? (Select the best answer.)",["Run 12 Reserved Instances all of the time.","Run four On-Demand Instances constantly, then add eight more On-Demand Instances on the last day of each month.","Run four Reserved Instances constantly, then add eight On-Demand Instances on the last day of each month.","Run four On-Demand Instances constantly, then add eight Reserved Instances on the last day of each month."],[2],"Reserved Instances provide cost savings when you can commit to running instances full time, such as to handle the base traffic. On-Demand Instances provide the flexibility to handle traffic spikes."],
["True or False? Containers contain an entire operating system.",["True","False"],[1],"Containers are smaller than virtual machines, and do not contain an entire operating system."],
["Which Amazon EC2 option is best for long-term workloads with predictable usage patterns? (Select the best answer.)",["Spot Instances","On-Demand Instances","Reserved Instances"],[2],"Reserved Instances would be the best EC2 option for long-term workloads with predictable usage patterns."],
["Which of the following must be specified when launching a new Amazon Elastic Compute Cloud (Amazon EC2) Windows instance? (Choose two.)",["Amazon EC2 instance type","Amazon Machine Image (AMI)","The Amazon EC2 instance ID","Password for the administrator account"],[0,1],"AWS assigns the EC2 instance ID as part of the launch process and the administrator password, which is encrypted via the public key. The instance type defines the virtual hardware and the AMI defines the initial software state. Both must be specified on launch."]
]},
{ id: "m7", code: "M07", title: "Storage", ru: "Хранилища", qs: [
["True or False? Amazon Simple Storage Service (Amazon S3) is an object storage suitable for the storage of flat files like Microsoft Word documents, photos, etc.",["True","False"],[0],"It’s true that S3 is an object storage suitable for the storage of 'flat' files like Word documents, photos, etc."],
["Amazon S3 replicates all objects ______. (Select the best answer.)",["on multiple volumes within an Availability Zone","in multiple Availability Zones within the same Region","across multiple Regions for higher durability","on multiple S3 buckets"],[1],"S3 replicates all objects in multiple Availability Zones within the same Region."],
["Which of the following can be used as a storage class for an S3 object lifecycle policy? (Choose three.)",["Simple Storage Service Glacier","S3 - Infrequent Access","S3 - Standard Access","Amazon DynamoDB","S3 - Reduced Redundancy Storage","AWS Storage Gateway"],[0,1,2],"Glacier, S3 Infrequent Access and S3 Standard Access can be used as a storage class for an S3 object lifecycle policy."],
["The name of an S3 bucket must be unique _________. (Select the best answer.)",["worldwide across all AWS accounts","within a Region","across all your AWS accounts","within your AWS account"],[0],"The name of an S3 bucket must be unique worldwide across all AWS accounts."],
["You can use Amazon Elastic File System (Amazon EFS) to: (Select the best answer.)",["provide simple, scalable, elastic file storage for use only within AWS.","implement storage for Amazon EC2 instances that multiple virtual machines can access at the same time.","host a robust CDN to deliver entire web sites with dynamic, static, and streaming content.","generate user-specific content."],[1],"You can use EFS to implement storage for EC2 instances that multiple virtual machines can access at the same time."],
["Amazon Elastic Block Store (Amazon EBS) is recommended when data _______ and _______. (Choose two.)",["requires an encryption solution","must be quickly accessible, requiring long-term persistence","needs to be stored in a different Availability Zone than the one the EC2 instance is in","requires object-level storage"],[0,1],"Amazon EBS is recommended when data must be quickly accessible, requiring long-term persistence and requires an encryption solution."],
["True or False? By default, all data stored in Amazon S3 is viewable by the public.",["True","False"],[1],"By default, all data stored in S3 is not viewable by the public."],
["Regarding Amazon S3 Glacier, what is a Vault? (Select the best answer.)",["The rules that determine who may (or may not) access archives","An object (photos, videos, files, or documents)","A container for storing archives","A policy that identifies who can access content stored in Glacier"],[2],"The vault in Amazon Glacier is a container for storing archives."],
["True or False? When you create a bucket in Amazon S3, it is associated with a specific AWS Region.",["True","False"],[0],"When you create a bucket in Amazon S3, it is associated with a specific AWS Region."],
["Which of the following are features of Amazon Elastic Block Store (Amazon EBS)? (Choose two.)",["Amazon EBS volumes can be encrypted transparently to workloads on the attached instance.","Data stored on Amazon EBS is automatically replicated within an Availability Zone.","Data on an Amazon EBS volume is lost when the attached instance is stopped.","Amazon EBS data is automatically backed up to tape."],[0,1],"Amazon EBS volumes persist when the instance is stopped. The data is automatically replicated within an Availability Zone, can be encrypted upon creation and used by an instance as if they were not encrypted."]
]},
{ id: "m8", code: "M08", title: "Databases", ru: "Базы данных", qs: [
["You are designing an ecommerce web application that will scale to hundreds of thousands of concurrent users. Which database technology is best suited to hold the session state in this example?",["Amazon Relational Database Service (Amazon RDS)","Amazon DynamoDB","Amazon Redshift","Amazon Simple Storage Service (Amazon S3)"],[1],"NoSQL databases like Amazon DynamoDB excel at scaling to hundreds of thousands of requests with key/value access to user profile and session."],
["You need to find an item in an Amazon DynamoDB table using an attribute other than the item’s primary key. Which of the following operations should you use? (Select the best answer.)",["PutItem","Scan","Query","GetItem"],[1],"To find an item in a DynamoDB table by an attribute other than the item's primary key, you would use the scan operation."],
["In Amazon DynamoDB, what does the query operation enable you to do? (Select the best answer.)",["Query a table using the partition key and an optional sort key filter","Query any secondary indexes that exist for a table","Efficiently retrieve items from a table or secondary index","All of the above"],[3],"In Amazon DynamoDB, the query operation allows you to do all of these things."],
["Which AWS Cloud service is best suited for analyzing your data by using standard structured query language (SQL) and your existing business intelligence (BI) tools? (Select the best answer.)",["Amazon Relational Database Service (Amazon RDS)","Amazon Simple Storage Service Glacier","Amazon DynamoDB","Amazon Redshift"],[3],"Amazon Redshift is best suited for analyzing data."],
["In Amazon DynamoDB, an attribute is ______. (Select the best answer.)",["a fundamental data element","a collection of items","a collection of attributes"],[0],"In Amazon DynamoDB, an attribute is a fundamental data element."],
["If you are developing an application that requires a database with extremely fast performance, fast scalability, and flexibility in the database schema, which service should you consider? (Select the best answer.)",["Amazon Relational Database Service (Amazon RDS)","Amazon ElastiCache","Amazon DynamoDB","Amazon Redshift"],[2],"If you are developing an application that requires a database with extremely fast performance, fast scalability, and flexibility in the database schema, consider Amazon DynamoDB."],
["Which of the following use cases is appropriate for using Amazon Relational Database Service (Amazon RDS)? (Select the best answer.)",["Massive read/write rates","Simple GET or PUT requests","Complex transactions","All of the above"],[2],"Use Amazon RDS when your application requires complex transactions or complex queries."],
["A company has an application, which consists of a .NET layer that connects to a MySQL database. They want to move this application on to AWS and use AWS features such as high availability and automated backups. Which of the following would be an ideal database for this use case? (Select the best answer.)",["Amazon Aurora","Amazon RDS","Amazon Redshift","Amazon DynamoDB"],[0],"Amazon Aurora is a MySQL- and PostgreSQL-compatible relational database that would be ideal for this use case."],
["True or false? Amazon RDS automatically patches the database software and backs up your database, storing the backups for a user-defined retention period and enabling point-in-time recovery.",["True","False"],[0],"Amazon RDS automatically patches the database software and backs up your database."],
["What should you consider when choosing a database type? (Select the best answer.)",["Data size","Data access period","Query frequency","Highly available","All of the above"],[4],"When choosing a database type, you should consider all of these."]
]},
{ id: "m9", code: "M09", title: "Cloud Architecture", ru: "Архитектура", qs: [
["Which of the following is not one of the four areas of the performance efficiency pillar of the AWS Well-Architected Framework? (Select the best answer.)",["Tradeoffs","Selection","Traceability","Monitoring"],[2],"Traceability is not one of the four areas of the Performance Efficiency pillar of the AWS Well-Architected Framework."],
["Which of the following is a principle when designing cloud-based systems? (Select the best answer.)",["Build tightly-coupled components","Make infrequent, large batch changes","Assume everything will fail","Use as many services as possible"],[2],"Assume everything will fail."],
["Which of the following are pillars of the AWS Well-Architected Framework? (Choose three.)",["Cost Optimization","Operational Excellence","Security","Persistence"],[0,1,2],"Operational excellence, security, and cost optimization are pillars of the AWS Well-Architected Framework."],
["Which design principles are recommended when considering performance efficiency? (Choose two.)",["Democratize advanced technologies","Use serverless architectures","Analyze and attribute expenditure","Enable traceability","Match supply with demand"],[0,1],"Use serverless architectures and democratize advanced technologies are design principles that are recommended when considering performance efficiency."],
["AWS Trusted Advisor provides insight regarding which five categories of an AWS account? (Select the best answer.)",["Security, fault tolerance, high availability, connectivity, service limits","Security, access control, high availability, performance, service limits","Performance, cost optimization, security, fault tolerance, service limits","Performance, cost optimization, access control, connectivity, security"],[2],"Performance, cost optimization, security, fault tolerance, and service limits are the five categories."],
["What is the focus of the sustainability pillar of the Well-Architected Framework? (Select the best answer.)",["Designing workloads that recover quickly from failures","Minimizing the environmental impacts of running cloud workloads","Avoiding unnecessary costs in cloud workloads","Automating updates to cloud workloads"],[1],"Key topics of the sustainability pillar include a shared responsibility model for sustainability, understanding impact, and maximizing utilization to minimize required resources and reduce downstream impacts."],
["After you move to the AWS Cloud, you want to ensure that the right security settings are put in place. Which online tool can assist in security compliance? (Select the best answer.)",["Amazon Kinesis","AWS Support","AWS Trusted Advisor","Amazon CloudWatch"],[2],"AWS Trusted Advisor is an online resource to help you reduce cost, increase performance, and improve security by optimizing your AWS environment."],
["Which of the following is a measure of your system’s ability to provide functionality when desired by the user? (Select the best answer.)",["Availability","Fault Tolerance","Reliability","Performance efficiency"],[2],"Reliability is a measure of your system’s ability to provide functionality when desired by the user."],
["What is defined as the ability for a system to remain operational even if some of the components of that system fail? (Select the best answer.)",["High durability","Fault tolerance","High availability"],[1],"Fault tolerance is the ability for a system to remain operational even if some of the components of that system fail."],
["Which of the following best describes a system that can withstand some measures of degradation, experiences minimal downtime, and requires minimal human intervention? (Select the best answer.)",["Scalable","Fault-tolerant","Elastic","Highly available"],[3],"A highly available system is always available, without the need for human intervention."]
]},
{ id: "m10", code: "M10", title: "Auto Scaling and Monitoring", ru: "Масштабирование и мониторинг", qs: [
["Which of the following AWS tools help your application scale up or down based on demand? (Choose two.)",["Elastic Load Balancing","Amazon EC2 Auto Scaling","AWS Config","AWS CloudFormation","Availability Zones"],[0,1],"Amazon EC2 Auto Scaling and Elastic Load Balancing help your application scale up or down based on demand."],
["Which service would you use to send alerts based on Amazon CloudWatch alarms? (Select the best answer.)",["Amazon Simple Notification Service (Amazon SNS)","AWS CloudTrail","AWS Trusted Advisor","Amazon Route 53"],[0],"Amazon SNS is the service you'd use to send alerts based on Amazon CloudWatch alarms."],
["Which of the following are characteristics of Amazon EC2 Auto Scaling? (Choose three.)",["Enforces a minimum number of running Amazon EC2 instances","Launches instances from a specified Amazon Machine Image (AMI)","Responds to changing conditions by adding or terminating instances","Delivers push notifications","Only supports dynamic scaling"],[0,1,2],"Amazon EC2 Auto Scaling responds to changing conditions by adding or terminating instances, launches instances from an AMI, and enforces a minimum number of running Amazon EC2 instances."],
["Which of the following must be configured on an Elastic Load Balancing load balancer to expect incoming traffic? (Select the best answer.)",["A port","A network interface","A listener","An instance"],[2],"You configure the load balancer to accept incoming traffic by specifying one or more listeners."],
["Which of the following elements are used to create an Amazon EC2 Auto Scaling launch configuration? (Choose three.)",["Amazon Elastic Block Store (Amazon EBS) volumes","Instance type","Amazon Machine Image (AMI)","Virtual private cloud (VPC) and subnets","Load balancer"],[0,1,2],"You specify the AMI, instance type, and EBS volumes when you create an Auto Scaling launch configuration."],
["Which of the following services can help you collect important metrics from Amazon Relational Database Service (Amazon RDS) and Amazon Elastic Compute Cloud (Amazon EC2) instances? (Select the best answer.)",["Amazon CloudFront","Amazon CloudSearch","Amazon CloudWatch","AWS CloudTrail","Amazon EC2 Auto Scaling"],[2],"Amazon CloudWatch is a monitoring service for AWS cloud resources and the applications you run on AWS."],
["Which of the following are elements of an Auto Scaling group? (Choose three.)",["Maximum size","Desired capacity","Minimum size","Health checks"],[0,1,2],"You can specify the minimum and maximum number of instances in each Auto Scaling group as well as desired capacity."],
["There is an audit at your company and they need to have a log of all access to AWS resources in the account. Which of the following services can assist in providing these details? (Select the best answer.)",["Amazon CloudWatch","AWS CloudTrail","Amazon Elastic Compute Cloud (Amazon EC2)","Amazon Simple Notification Service (Amazon SNS)"],[1],"AWS CloudTrail is a service that enables governance, compliance, operational auditing, and risk auditing of your AWS account."],
["In Elastic Load Balancing, when the load balancer detects an unhealthy target, which of the following are true? (Choose three.)",["Routes traffic to a healthy target","Resumes routing traffic when it detects that the target is healthy again","Stops routing traffic to that target","Resumes routing traffic when manually restarted","Triggers an alarm"],[0,1,2],"When the load balancer detects an unhealthy target, it stops routing traffic to that target and sends it to a healthy target. It then resumes routing traffic to that target when it detects that the target is healthy again."],
["What are the three types of load balancers that Elastic Load Balancing offers? (Choose three.)",["Classic Load Balancer","Network Load Balancer","Application Load Balancer","Auto Scaling Load Balancer","Compute Load Balancer","Internet Load Balancer"],[0,1,2],"ELB offers three types of load balancers: Application Load Balancer, Network Load Balancer, and Classic Load Balancer."]
]}
];
