// Computer Networks: тест по лекциям 1–5 (вопросы в стиле Cisco ITN).
// Формат: { l: лекция, q: вопрос (EN), o: варианты (EN), a: индекс верного или массив для «Choose two» (по умолчанию 0),
//           e: пояснение (RU) }. Варианты перемешиваются при показе. `текст` в обратных кавычках рисуется как код.
// id вопроса = лекция + ":" + номер внутри лекции, поэтому новые вопросы добавляй в конец своей лекции.
window.NET_LECS = [
  { k: "1", s: "L1", t: "Networking Today & IOS", ru: "Компоненты, LAN/WAN, надёжность, режимы IOS, базовая настройка" },
  { k: "2", s: "L2", t: "Protocols and Models", ru: "Правила, TCP/IP и OSI, стандарты, PDU, инкапсуляция" },
  { k: "3", s: "L3", t: "Physical Layer", ru: "Encoding, bandwidth, медь, оптика, Wi-Fi" },
  { k: "4", s: "L4", t: "Data Link & Ethernet Switching", ru: "LLC/MAC, CSMA, кадр Ethernet, MAC-адреса, MAC-таблица" },
  { k: "5", s: "L5", t: "Network Layer, ARP, Router Config", ru: "IPv4/IPv6, шлюз, маршруты, ARP, настройка роутера" }
];

window.NET_QUIZ = [
/* ---------------- L1 ---------------- */
{ l: "1", q: "Which term describes a computer on a network that provides information, such as web pages or email, to other devices?",
  o: ["Server", "Client", "Intermediary device", "Peer"],
  e: "Server предоставляет информацию (email, web, file server); client отправляет запросы серверу." },
{ l: "1", q: "What is a disadvantage of a peer-to-peer network?",
  o: ["No centralized administration", "Complex to set up", "High cost", "Requires a dedicated server"],
  e: "P2P прост и дёшев, но в нём нет централизованного администрирования, он менее безопасен, плохо масштабируется и медленнее." },
{ l: "1", q: "Which two devices are intermediary devices? (Choose two.)",
  o: ["Switch", "Wireless access point", "Laptop", "IP phone", "Network printer"], a: [0, 1],
  e: "Intermediary devices соединяют конечные: switch, wireless AP, router, firewall. Laptop, IP phone и принтер — end devices." },
{ l: "1", q: "Which function is performed by an intermediary device?",
  o: ["Regenerate and retransmit data signals", "Originate a message", "Act as the final destination of data", "Run end-user applications"],
  e: "Промежуточные устройства регенерируют и передают сигналы, хранят информацию о путях, уведомляют об ошибках. Сообщения начинаются и заканчиваются на end devices." },
{ l: "1", q: "Which network medium uses pulses of light to carry data?",
  o: ["Fiber-optic cable", "Copper cable", "Wireless", "Coaxial cable"],
  e: "Медь — электрические импульсы, оптоволокно — импульсы света, беспроводная среда — модуляция частот электромагнитных волн." },
{ l: "1", q: "Which type of diagram shows the devices, ports and IP addressing scheme of a network?",
  o: ["Logical topology diagram", "Physical topology diagram", "Wiring diagram", "Floor plan"],
  e: "Logical topology — устройства, порты и схема адресации. Physical topology — физическое расположение устройств и кабелей." },
{ l: "1", q: "Which statement describes a characteristic of a WAN?",
  o: ["It is typically administered by one or more service providers", "It spans a small geographic area", "It provides the highest-speed bandwidth to internal devices", "It is administered by a single individual"],
  e: "WAN соединяет LAN на большой территории, обычно управляется провайдерами и даёт более медленные каналы. Остальное про LAN." },
{ l: "1", q: "Which network type allows secure access for people who work for a different organization, such as suppliers?",
  o: ["Extranet", "Intranet", "LAN", "SOHO"],
  e: "Intranet — только для членов организации. Extranet даёт безопасный доступ людям из другой организации, которым нужны её данные." },
{ l: "1", q: "Which organizations help maintain the structure of the internet? (Choose two.)",
  o: ["IETF", "ICANN", "Cisco", "Microsoft", "ISP"], a: [0, 1],
  e: "Интернет никому не принадлежит; структуру поддерживают IETF, ICANN и IAB." },
{ l: "1", q: "Which home internet connection runs over a telephone line?",
  o: ["DSL", "Cable", "Satellite", "Cellular"],
  e: "DSL — always-on по телефонной линии. Cable — от провайдера кабельного ТВ." },
{ l: "1", q: "Which internet connection type is a major benefit for rural areas that have no other ISP?",
  o: ["Satellite", "DSL", "Cable", "Metro Ethernet"],
  e: "Satellite полезен там, где нет проводных провайдеров." },
{ l: "1", q: "Which business connection uses reserved circuits within the service provider's network to connect distant offices?",
  o: ["Dedicated leased line", "Dial-up", "Cellular", "Powerline"],
  e: "Leased line — зарезервированные каналы в сети провайдера для частной голосовой и/или передачи данных между офисами." },
{ l: "1", q: "What is a converged network?",
  o: ["A network that carries data, voice and video over the same infrastructure", "A network with separate cabling for telephone, video and data", "A network that uses only wireless media", "A network that connects only two LANs"],
  e: "Converged network несёт данные, голос и видео по одной инфраструктуре с одними правилами и стандартами." },
{ l: "1", q: "Which network characteristic limits the impact of a failure by providing multiple paths?",
  o: ["Fault tolerance", "Scalability", "Quality of service", "Security"],
  e: "Fault tolerance: несколько путей и packet switching, чтобы сбой затрагивал как можно меньше устройств." },
{ l: "1", q: "Why does packet switching make a network more fault tolerant than circuit switching?",
  o: ["Each packet can take a different path to the destination", "It establishes a dedicated circuit for every call", "It encrypts every packet", "It reserves bandwidth for voice"],
  e: "Пакеты маршрутизируются независимо и могут обойти сбой. Circuit switching держит выделенный канал, его обрыв рвёт связь." },
{ l: "1", q: "A network can expand quickly to support new users without degrading service for existing users. Which characteristic is this?",
  o: ["Scalability", "Fault tolerance", "QoS", "Integrity"],
  e: "Scalability; достигается следованием стандартам и протоколам." },
{ l: "1", q: "A live video keeps pausing because demand for bandwidth exceeds what is available. Which mechanism should be configured?",
  o: ["Quality of Service (QoS)", "Fault tolerance", "BYOD", "Packet switching"],
  e: "QoS — главный механизм надёжной доставки голоса и видео; с QoS-политикой роутер управляет потоками трафика." },
{ l: "1", q: "Which goal of network security ensures that only the intended recipients can read the data?",
  o: ["Confidentiality", "Integrity", "Availability", "Scalability"],
  e: "Confidentiality — читают только адресаты; integrity — данные не изменены; availability — своевременный доступ для авторизованных." },
{ l: "1", q: "Which trend means 'any device, with any ownership, used anywhere'?",
  o: ["BYOD", "Cloud computing", "Powerline networking", "Video communication"],
  e: "Bring Your Own Device: личные ноутбуки, планшеты и смартфоны для доступа к информации." },
{ l: "1", q: "Which cloud type is built to meet the needs of a specific industry, such as healthcare?",
  o: ["Custom cloud", "Public cloud", "Private cloud", "Hybrid cloud"],
  e: "Custom cloud — под конкретную отрасль (здравоохранение, медиа), может быть private или public." },
{ l: "1", q: "Which technology lets a device connect to a LAN through a standard electrical outlet?",
  o: ["Powerline networking", "Wireless broadband", "DSL", "Satellite"],
  e: "Powerline adapter передаёт данные на определённых частотах по электропроводке." },
{ l: "1", q: "Which access method is recommended for remotely connecting to a network device?",
  o: ["SSH", "Telnet", "Console", "AUX"],
  e: "SSH — защищённое удалённое подключение. Telnet передаёт логин, пароли и команды открытым текстом. Console — физический порт." },
{ l: "1", q: "Which access method requires no network connection and is used for the initial configuration of a switch?",
  o: ["Console", "SSH", "Telnet", "HTTP"],
  e: "Console — физический management port для обслуживания и начальной настройки." },
{ l: "1", q: "Which part of an operating system communicates between the hardware and the software?",
  o: ["Kernel", "Shell", "GUI", "CLI"],
  e: "Kernel связывает железо и ПО и распределяет ресурсы. Shell — интерфейс пользователя (CLI или GUI)." },
{ l: "1", q: "Which prompt indicates privileged EXEC mode?",
  o: ["`Switch#`", "`Switch>`", "`Switch(config)#`", "`Switch(config-if)#`"],
  e: "`>` — user EXEC, `#` без скобок — privileged EXEC, `(config)#` — global configuration." },
{ l: "1", q: "Which command moves a switch from user EXEC mode to privileged EXEC mode?",
  o: ["`enable`", "`configure terminal`", "`exit`", "`login`"],
  e: "`enable` → privileged EXEC; `configure terminal` из privileged EXEC → global config." },
{ l: "1", q: "An administrator is in interface configuration mode. Which command returns directly to privileged EXEC mode?",
  o: ["`end`", "`exit`", "`disable`", "`logout`"],
  e: "`end` (или Ctrl+Z) возвращает из любого режима конфигурации сразу в privileged EXEC. `exit` поднимает на один уровень, в global config." },
{ l: "1", q: "In the command `Switch> ping 192.168.10.5`, what is `192.168.10.5`?",
  o: ["Argument", "Keyword", "Prompt", "Command"],
  e: "Argument — значение, заданное пользователем. Keyword — параметр, определённый в IOS (например `ip protocols`)." },
{ l: "1", q: "In command syntax notation, what do square brackets [x] indicate?",
  o: ["An optional element", "A required element", "An argument the user must supply", "A keyword entered literally"],
  e: "[x] — необязательный элемент, {x} — обязательный, курсив — аргумент, жирный — ввести буквально." },
{ l: "1", q: "Which keystroke completes a partially entered command in the IOS CLI?",
  o: ["Tab", "Ctrl+Z", "Ctrl+Shift+6", "Up Arrow"],
  e: "Tab дополняет команду; ↑ вызывает историю; Ctrl+Shift+6 прерывает ping и traceroute; Ctrl+Z выходит в privileged EXEC." },
{ l: "1", q: "Which key sequence is the all-purpose break used to abort DNS lookups, traceroutes and pings?",
  o: ["Ctrl+Shift+6", "Ctrl+Z", "Ctrl+B", "Ctrl+P"],
  e: "Ctrl+Shift+6 — универсальный break." },
{ l: "1", q: "Which hostname follows the Cisco naming guidelines?",
  o: ["`Sw-Floor-1`", "`1-Switch`", "`Floor 1 Switch`", "`Switch-`"],
  e: "Имя начинается с буквы, без пробелов, заканчивается буквой или цифрой, только буквы, цифры и дефисы, меньше 64 символов." },
{ l: "1", q: "Which command secures privileged EXEC mode with an encrypted password?",
  o: ["`enable secret class`", "`enable password class`", "`password class`", "`login class`"],
  e: "`enable secret` хранит пароль в зашифрованном (хешированном) виде; это рекомендованный способ." },
{ l: "1", q: "After `line console 0` and `password cisco`, which command is needed so that the password is actually required?",
  o: ["`login`", "`enable`", "`service password-encryption`", "`transport input ssh`"],
  e: "Без `login` пароль на линии не запрашивается." },
{ l: "1", q: "Which command enters the configuration mode for remote Telnet and SSH access on a switch with 16 lines?",
  o: ["`line vty 0 15`", "`line console 0`", "`line aux 0`", "`interface vlan 1`"],
  e: "VTY lines — виртуальные линии для Telnet/SSH; у многих коммутаторов их 16 (0–15)." },
{ l: "1", q: "Which command encrypts all plaintext passwords in the configuration?",
  o: ["`service password-encryption`", "`enable secret`", "`encrypt all`", "`password encryption aes`"],
  e: "`service password-encryption` в global config шифрует все пароли, которые иначе видны в running-config открытым текстом." },
{ l: "1", q: "In `banner motd # Authorized Access Only #`, what is the `#` character?",
  o: ["The delimiting character", "A comment marker", "The privileged EXEC prompt", "A required password"],
  e: "Delimiting character ставится до и после текста баннера." },
{ l: "1", q: "Where is the startup-config file stored?",
  o: ["NVRAM", "RAM", "Flash only in volatile memory", "ROM cache"],
  e: "startup-config — в NVRAM, не теряется при выключении. running-config — в RAM, теряется." },
{ l: "1", q: "What happens to the running configuration when a switch loses power and it was never saved?",
  o: ["The changes are lost because RAM is volatile", "The changes are kept in NVRAM", "The switch reloads the changes from flash", "The changes are copied to the startup-config automatically"],
  e: "running-config хранится в RAM: всё несохранённое теряется. Сохранять: `copy running-config startup-config`." },
{ l: "1", q: "Which command saves the current configuration so it is used after the next reboot?",
  o: ["`copy running-config startup-config`", "`copy startup-config running-config`", "`write erase`", "`reload`"],
  e: "Копирует running-config (RAM) в startup-config (NVRAM)." },
{ l: "1", q: "Unwanted changes were saved to the startup-config. Which two steps return the switch to a default configuration? (Choose two.)",
  o: ["`erase startup-config`", "`reload`", "`copy running-config startup-config`", "`no hostname`", "`end`"], a: [0, 1],
  e: "Стереть startup-config в NVRAM, затем `reload`, чтобы очистить running-config в RAM." },

/* ---------------- L2 ---------------- */
{ l: "2", q: "Which two elements are present in any communication? (Choose two.)",
  o: ["A source and a destination", "A channel (media)", "A firewall", "A DHCP server", "A default gateway"], a: [0, 1],
  e: "Любая коммуникация: source (отправитель), destination (получатель) и channel / media." },
{ l: "2", q: "What is the process of converting information into another acceptable form for transmission?",
  o: ["Encoding", "Encapsulation", "Segmentation", "Flow control"],
  e: "Encoding превращает информацию в форму для передачи; decoding — обратный процесс." },
{ l: "2", q: "Which message timing element manages the rate of data transmission and how much information can be sent?",
  o: ["Flow control", "Response timeout", "Access method", "Encoding"],
  e: "Flow control — скорость и объём; response timeout — сколько ждать ответа; access method — когда можно передавать." },
{ l: "2", q: "Which message timing element determines how long a device waits when it does not hear a reply?",
  o: ["Response timeout", "Flow control", "Access method", "Sequencing"],
  e: "Response timeout задаёт время ожидания ответа от получателя." },
{ l: "2", q: "What is a collision?",
  o: ["More than one device sends traffic at the same time and the messages become corrupt", "A frame arrives out of order", "A packet exceeds the MTU", "A switch floods a broadcast"],
  e: "Коллизия — одновременная передача нескольких устройств; access method определяет, когда можно отправлять." },
{ l: "2", q: "Which delivery option sends a message from one host to a group of hosts, but typically not all?",
  o: ["Multicast", "Unicast", "Broadcast", "Anycast"],
  e: "Unicast — одному, multicast — группе, broadcast — всем." },
{ l: "2", q: "Which delivery option is NOT available in IPv6?",
  o: ["Broadcast", "Unicast", "Multicast", "Anycast"],
  e: "В IPv6 нет broadcast; вместо него multicast, добавлен anycast." },
{ l: "2", q: "Which type of protocol enables routers to exchange route information and select the best path?",
  o: ["Routing", "Service discovery", "Network security", "Network communications"],
  e: "Routing protocols обмениваются маршрутами и выбирают лучший путь. Service discovery — автоматическое обнаружение устройств и сервисов." },
{ l: "2", q: "Which protocol function uniquely labels each transmitted segment of data?",
  o: ["Sequencing", "Addressing", "Reliability", "Error detection"],
  e: "Sequencing нумерует сегменты для сборки; addressing — отправитель и получатель; reliability — гарантированная доставка." },
{ l: "2", q: "Which protocol function provides guaranteed delivery?",
  o: ["Reliability", "Flow control", "Application interface", "Addressing"],
  e: "Reliability — гарантированная доставка (в TCP/IP это делает TCP)." },
{ l: "2", q: "Which protocol governs the way a web server and a web client interact?",
  o: ["HTTP", "TCP", "IP", "Ethernet"],
  e: "HTTP — взаимодействие веб-сервера и клиента; TCP — разговоры и доставка; IP — глобальная доставка; Ethernet — NIC к NIC в LAN." },
{ l: "2", q: "Which protocol manages individual conversations, provides guaranteed delivery and flow control?",
  o: ["TCP", "IP", "HTTP", "Ethernet"],
  e: "TCP — транспортный протокол с гарантией доставки и flow control." },
{ l: "2", q: "Which protocol delivers messages from one NIC to another NIC on the same Ethernet LAN?",
  o: ["Ethernet", "IP", "TCP", "HTTP"],
  e: "Ethernet доставляет в пределах LAN; IP — глобально от источника до получателя." },
{ l: "2", q: "What is a protocol suite?",
  o: ["A group of inter-related protocols necessary to perform a communication function", "A single protocol used by all vendors", "A hardware device that runs protocols", "A list of standards organizations"],
  e: "Protocol suite — набор взаимосвязанных протоколов, которые вместе решают задачу коммуникации." },
{ l: "2", q: "Which organization maintains the TCP/IP protocol suite?",
  o: ["IETF", "IEEE", "ISO", "EIA"],
  e: "TCP/IP поддерживает IETF. OSI разработали ISO и ITU." },
{ l: "2", q: "Which two statements describe TCP/IP? (Choose two.)",
  o: ["It is an open standard freely available to the public", "It is standards-based and endorsed by the networking industry", "It is a proprietary suite developed by Apple", "It was developed by Novell", "It specifies only physical layer protocols"], a: [0, 1],
  e: "TCP/IP — open standard (любой вендор) и standards-based (одобрен для interoperability). AppleTalk и NetWare — проприетарные." },
{ l: "2", q: "Which two protocols are the most common network access layer LAN protocols? (Choose two.)",
  o: ["Ethernet", "WLAN (802.11)", "TCP", "HTTP", "IPv4"], a: [0, 1],
  e: "На network access уровне LAN чаще всего Ethernet и WLAN." },
{ l: "2", q: "Which protocol operates at the transport layer of the TCP/IP model?",
  o: ["UDP", "IPv4", "DHCP", "Ethernet"],
  e: "Transport: TCP и UDP. IPv4 — internet layer, DHCP — application, Ethernet — network access." },
{ l: "2", q: "Which organization promotes the open development and evolution of internet use throughout the world?",
  o: ["ISOC", "IANA", "TIA", "IEEE"],
  e: "Internet Society (ISOC). IAB — управление стандартами интернета; IETF — разработка; IRTF — долгосрочные исследования." },
{ l: "2", q: "Which organization oversees IP address allocation, domain name management and protocol identifiers for ICANN?",
  o: ["IANA", "IETF", "IEEE", "ISO"],
  e: "IANA управляет адресами, доменами и идентификаторами протоколов для ICANN." },
{ l: "2", q: "Which organization develops standards such as 802.3 Ethernet and 802.11 wireless LANs?",
  o: ["IEEE", "IETF", "EIA", "ITU-T"],
  e: "IEEE («I-triple-E») — стандарты для энергетики, медицины, телекома и сетей." },
{ l: "2", q: "Which organization develops standards for electrical wiring, connectors and 19-inch equipment racks?",
  o: ["EIA", "TIA", "ITU-T", "IANA"],
  e: "EIA — проводка, разъёмы, стойки. TIA — радиооборудование, вышки, VoIP, спутники. ITU-T — видео, IPTV, DSL." },
{ l: "2", q: "Which organization defines standards for video compression, IPTV and broadband communications such as DSL?",
  o: ["ITU-T", "EIA", "IAB", "IRTF"],
  e: "ITU-T — сектор стандартизации телекоммуникаций ITU." },
{ l: "2", q: "What is a benefit of using a layered model?",
  o: ["It prevents changes in one layer from affecting other layers", "It forces all vendors to use the same hardware", "It removes the need for protocols", "It makes networks proprietary"],
  e: "Плюсы: помогает проектировать протоколы, поощряет конкуренцию вендоров, изолирует изменения уровней, даёт общий язык." },
{ l: "2", q: "Which OSI layer provides for common representation of the data transferred between application layer services?",
  o: ["Presentation", "Session", "Application", "Transport"],
  e: "Presentation (6) — представление данных (формат, сжатие, шифрование). Session (5) — управление обменом данными." },
{ l: "2", q: "Which OSI layer defines services to segment, transfer and reassemble data for individual communications?",
  o: ["Transport", "Network", "Data link", "Session"],
  e: "Transport (4) — сегментация и сборка. Network (3) — обмен кусками данных по сети." },
{ l: "2", q: "Which OSI layer describes methods for exchanging data frames over a common media?",
  o: ["Data link", "Physical", "Network", "Transport"],
  e: "Data link (2) — кадры через общую среду. Physical (1) — активировать и поддерживать физические соединения." },
{ l: "2", q: "Which TCP/IP layer determines the best path through the network?",
  o: ["Internet", "Transport", "Network access", "Application"],
  e: "Internet layer TCP/IP = network layer OSI: лучший путь и IP." },
{ l: "2", q: "The TCP/IP application layer corresponds to which OSI layers?",
  o: ["Application, presentation and session", "Application only", "Application and transport", "Session and transport"],
  e: "OSI делит application уровень TCP/IP на 3: application, presentation, session." },
{ l: "2", q: "The TCP/IP network access layer corresponds to which OSI layers?",
  o: ["Data link and physical", "Network and data link", "Physical only", "Transport and network"],
  e: "Network access TCP/IP = OSI 2 (data link) + 1 (physical)." },
{ l: "2", q: "What are two benefits of segmenting messages? (Choose two.)",
  o: ["Increases speed: large amounts of data do not tie up a link", "Increases efficiency: only failed segments are retransmitted", "Removes the need for addressing", "Guarantees delivery without TCP", "Encrypts the data"], a: [0, 1],
  e: "Сегментация повышает скорость и эффективность: переотправляются только потерянные сегменты." },
{ l: "2", q: "What is multiplexing?",
  o: ["Interleaving multiple streams of segmented data on one link", "Breaking a message into smaller units", "Numbering segments for reassembly", "Converting bits to signals"],
  e: "Segmenting — разбиение; multiplexing — чередование нескольких потоков; sequencing — нумерация." },
{ l: "2", q: "Which protocol is responsible for sequencing the individual segments?",
  o: ["TCP", "IP", "Ethernet", "HTTP"],
  e: "TCP нумерует сегменты, чтобы получатель собрал сообщение." },
{ l: "2", q: "What is the PDU at the network layer called?",
  o: ["Packet", "Segment", "Frame", "Bits"],
  e: "Data → segment (transport) → packet (network) → frame (data link) → bits (physical)." },
{ l: "2", q: "What is the PDU at the transport layer called?",
  o: ["Segment", "Packet", "Frame", "Data stream"],
  e: "Transport layer работает с segments." },
{ l: "2", q: "What is the correct order of PDUs during encapsulation, from the application down?",
  o: ["Data, segment, packet, frame, bits", "Data, packet, segment, frame, bits", "Bits, frame, packet, segment, data", "Data, frame, packet, segment, bits"],
  e: "Инкапсуляция сверху вниз: data → segment → packet → frame → bits. Деинкапсуляция — обратный порядок." },
{ l: "2", q: "What happens during de-encapsulation?",
  o: ["Each layer removes its header and passes the data up to the next layer", "Each layer adds a header and passes the data down", "The data is converted to a bit stream", "The data is segmented into smaller pieces"],
  e: "De-encapsulation — снизу вверх у получателя: каждый уровень снимает свой заголовок." },

/* ---------------- L3 ---------------- */
{ l: "3", q: "What is the purpose of the physical layer?",
  o: ["To transmit bits across the local media", "To select the best path through the network", "To provide physical addressing with MAC addresses", "To segment data for reassembly"],
  e: "Physical layer кодирует кадр в сигналы и передаёт биты; это последний шаг инкапсуляции." },
{ l: "3", q: "What does the physical layer accept from the data link layer?",
  o: ["A complete frame", "A segment", "A packet", "A data stream"],
  e: "Physical layer получает целый кадр и кодирует его в серию сигналов." },
{ l: "3", q: "Which two functional areas are addressed by physical layer standards, besides physical components? (Choose two.)",
  o: ["Encoding", "Signaling", "Logical addressing", "Routing", "Error correction with ACKs"], a: [0, 1],
  e: "Стандарты физического уровня: physical components, encoding и signaling." },
{ l: "3", q: "Which encoding method is shown as an example in the physical layer standards and uses a transition in the middle of each bit time?",
  o: ["Manchester", "Base64", "ASCII", "Unicode"],
  e: "Manchester (также 4B/5B и 8B/10B) — методы кодирования физического уровня." },
{ l: "3", q: "Which term describes how bit values 1 and 0 are represented on the physical medium?",
  o: ["Signaling", "Encoding", "Framing", "Multiplexing"],
  e: "Signaling: электрические сигналы по меди, свет по оптике, микроволны по беспроводной среде." },
{ l: "3", q: "What is the capacity at which a medium can carry data?",
  o: ["Bandwidth", "Throughput", "Goodput", "Latency"],
  e: "Bandwidth — ёмкость среды; throughput — реально переданное; goodput — полезные данные." },
{ l: "3", q: "Which term describes the measure of usable data transferred over a given period of time?",
  o: ["Goodput", "Throughput", "Bandwidth", "Latency"],
  e: "Goodput = throughput − traffic overhead." },
{ l: "3", q: "What is latency?",
  o: ["The amount of time, including delays, for data to travel from one point to another", "The number of bits transmitted per second", "The usable data per second", "The maximum cable length"],
  e: "Latency — время прохождения данных вместе с задержками." },
{ l: "3", q: "How many bits per second is 1 Gbps?",
  o: ["1,000,000,000 bps", "1,000,000 bps", "1,024 bps", "1,000,000,000,000 bps"],
  e: "Kbps = 10³, Mbps = 10⁶, Gbps = 10⁹, Tbps = 10¹² бит в секунду." },
{ l: "3", q: "Which copper cabling limitation is mitigated by strict adherence to cable length limits?",
  o: ["Attenuation", "Crosstalk", "EMI", "RFI"],
  e: "Attenuation — ослабление сигнала с расстоянием; против него — ограничения длины." },
{ l: "3", q: "How do UTP cables mitigate crosstalk?",
  o: ["By twisting opposing circuit pair wires together", "By using a metallic foil shield", "By using a copper braid", "By using light instead of electricity"],
  e: "Скручивание пар с противоположной полярностью (cancellation). Экран и заземление — против EMI/RFI." },
{ l: "3", q: "Which property of UTP cabling makes the magnetic fields of a wire pair cancel each other and outside EMI/RFI?",
  o: ["Cancellation", "Attenuation", "Dispersion", "Modulation"],
  e: "Cancellation: провода пары с противоположной полярностью скручены вместе." },
{ l: "3", q: "Which connector terminates UTP cable?",
  o: ["RJ-45", "BNC", "SC", "LC"],
  e: "UTP и STP терминируются RJ-45. SC и LC — оптические разъёмы, BNC — коаксиальный." },
{ l: "3", q: "Compared with UTP, what is true about STP?",
  o: ["It provides better noise protection but is more expensive and harder to install", "It is cheaper and easier to install", "It uses fiber strands", "It does not use RJ-45 connectors"],
  e: "STP: экран защищает от EMI/RFI лучше, но кабель дороже и сложнее в монтаже." },
{ l: "3", q: "Which type of copper cable is commonly used to attach antennas to wireless devices and for cable internet installations?",
  o: ["Coaxial", "UTP", "STP", "Rollover"],
  e: "Coax: антенны беспроводных устройств и кабельный интернет у клиента." },
{ l: "3", q: "What is the maximum cable length of UTP for most Ethernet speeds?",
  o: ["100 m", "550 m", "30 m", "1000 m"],
  e: "UTP — до 100 м (для 40 Gbps 30 м). 550 м — это MMF на 10 Gbps." },
{ l: "3", q: "Which standard specifies UTP cable types, lengths, connectors, termination and testing methods?",
  o: ["TIA/EIA-568", "IEEE 802.11", "ITU-T G.992", "RFC 791"],
  e: "TIA/EIA-568 — стандарт кабельной разводки; категории (Cat 5e, Cat 6) задают электрические характеристики." },
{ l: "3", q: "Which cable type should connect a switch to a PC?",
  o: ["Straight-through", "Crossover", "Rollover", "Coaxial"],
  e: "Разные устройства (switch–PC, switch–router, switch–server) соединяются straight-through." },
{ l: "3", q: "Which two connections require a crossover UTP cable? (Choose two.)",
  o: ["Switch to switch", "Router to router", "Switch to PC", "Switch to router", "Switch to server"], a: [0, 1],
  e: "Crossover — однотипные устройства: switch–switch, router–router, PC–PC, router–PC." },
{ l: "3", q: "What are two characteristics of fiber-optic cable? (Choose two.)",
  o: ["It is completely immune to EMI and RFI", "It transmits data over longer distances at higher bandwidth than other media", "It is the least expensive medium", "It uses electrical pulses", "It is easier to install than UTP"], a: [0, 1],
  e: "Fiber невосприимчив к EMI/RFI, дальше и быстрее любой среды, но дороже и требует больше навыков." },
{ l: "3", q: "Which statement describes single-mode fiber?",
  o: ["It has a very small core and uses expensive lasers for long distances", "It has a larger core and uses LEDs", "It is limited to 550 meters", "It has greater dispersion than multimode"],
  e: "SMF: маленькое ядро, лазер, большие расстояния. MMF: большое ядро, LED, до 10 Gbps на 550 м." },
{ l: "3", q: "Why is multimode fiber limited to shorter distances than single-mode fiber?",
  o: ["It has greater dispersion", "It is susceptible to EMI", "It uses electrical signals", "It cannot use LC connectors"],
  e: "Dispersion — растягивание импульса во времени; в MMF она больше, поэтому максимум 550 м." },
{ l: "3", q: "Which jacket color is typically used for single-mode fiber cables?",
  o: ["Yellow", "Orange", "Aqua", "Blue"],
  e: "Жёлтый — single-mode; оранжевый или aqua — multimode." },
{ l: "3", q: "Which fiber-optic usage provides always-on broadband services to homes and small businesses?",
  o: ["FTTH", "Long-haul networks", "Submarine cable networks", "Enterprise backbone"],
  e: "FTTH — Fiber-to-the-Home. Long-haul — между городами и странами, submarine — трансокеанские." },
{ l: "3", q: "Which two are fiber-optic connectors? (Choose two.)",
  o: ["SC", "LC", "RJ-45", "RJ-11", "BNC"], a: [0, 1],
  e: "Оптические разъёмы: ST, SC, LC (simplex и duplex)." },
{ l: "3", q: "What is a limitation of wireless media?",
  o: ["WLANs operate in half-duplex, so only one device can send or receive at a time", "It is completely immune to interference", "It requires physical access to the medium", "It offers no mobility"],
  e: "Ограничения беспроводной среды: coverage area, interference, security, shared medium (half-duplex)." },
{ l: "3", q: "Which IEEE standard defines Wi-Fi wireless LANs?",
  o: ["802.11", "802.15", "802.16", "802.3"],
  e: "802.11 — Wi-Fi, 802.15 — Bluetooth (WPAN), 802.16 — WiMAX, 802.3 — Ethernet." },
{ l: "3", q: "Which wireless standard is designed for low data-rate, low power-consumption IoT communications?",
  o: ["Zigbee (802.15.4)", "WiMAX (802.16)", "Wi-Fi (802.11ac)", "Bluetooth (802.15)"],
  e: "Zigbee — низкая скорость и энергопотребление, IoT." },
{ l: "3", q: "Which device concentrates wireless signals from users and connects them to the existing copper-based network?",
  o: ["Wireless access point", "Wireless NIC", "Hub", "Modem"],
  e: "WLAN = AP (подключает беспроводных клиентов к медной инфраструктуре) + wireless NIC на хостах." },
{ l: "3", q: "What is the SSID?",
  o: ["The name of a wireless network", "The MAC address of a wireless client", "A 5 GHz channel number", "The encryption key"],
  e: "SSID — имя беспроводной сети. BSSID — MAC-адрес радио AP." },
{ l: "3", q: "Which three channels are the non-overlapping channels in the 2.4 GHz band in the US and Europe?",
  o: ["1, 6 and 11", "1, 5 and 9", "2, 7 and 12", "1, 7 and 13"],
  e: "В 2.4 GHz непересекающиеся каналы 1, 6, 11 (в Японии ещё 14)." },
{ l: "3", q: "What is an advantage of the 5 GHz band over the 2.4 GHz band?",
  o: ["More non-overlapping channels and a less crowded spectrum", "Greater range", "Better propagation through walls", "Support by all older devices"],
  e: "5 GHz: больше каналов, меньше помех; но хуже распространение и старые устройства не поддерживают. 2.4 GHz дальше, но тесно." },
{ l: "3", q: "Which 802.11 amendment operates in both the 2.4 GHz and 5 GHz bands?",
  o: ["802.11n", "802.11a", "802.11b", "802.11ac"],
  e: "802.11n — 2.4 и 5 GHz, до 600 Mbps. 802.11a и ac — только 5 GHz; b и g — только 2.4 GHz." },
{ l: "3", q: "A device reports an RSSI of −60 dBm with a noise level of −100 dBm. What is the SNR?",
  o: ["40 dB", "−160 dB", "160 dB", "−40 dB"],
  e: "SNR = RSSI − Noise = −60 − (−100) = 40 dB." },
{ l: "3", q: "What does amplitude describe in a radio signal?",
  o: ["The strength of the signal", "How often the signal is seen per second", "The length of one cycle", "The channel width"],
  e: "Amplitude — сила; frequency — циклы в секунду (Hz); wavelength — длина цикла." },

/* ---------------- L4 ---------------- */
{ l: "4", q: "Which layer encapsulates Layer 3 packets into Layer 2 frames?",
  o: ["Data link layer", "Physical layer", "Network layer", "Transport layer"],
  e: "Data link layer даёт верхним уровням доступ к среде и инкапсулирует пакеты IPv4/IPv6 в кадры." },
{ l: "4", q: "What does the data link layer do with corrupted frames?",
  o: ["It detects the errors and rejects the frames", "It repairs them with error correction", "It forwards them to the router", "It requests retransmission from the application"],
  e: "Data link layer обнаруживает ошибки (FCS) и отбрасывает испорченные кадры." },
{ l: "4", q: "Which data link sublayer places information in the frame to identify which network layer protocol is used?",
  o: ["LLC", "MAC", "PHY", "CSMA"],
  e: "LLC (IEEE 802.2) — связь с ПО верхних уровней и идентификация L3 протокола. MAC — инкапсуляция и доступ к среде." },
{ l: "4", q: "Which data link sublayer is responsible for data encapsulation and media access control?",
  o: ["MAC", "LLC", "Network", "Session"],
  e: "MAC sublayer (802.3, 802.11, 802.15) — инкапсуляция, доступ к среде и адресация L2." },
{ l: "4", q: "Which IEEE standard defines the LLC sublayer?",
  o: ["802.2", "802.3", "802.11", "802.15"],
  e: "LLC — 802.2; MAC для Ethernet — 802.3, для Wi-Fi — 802.11." },
{ l: "4", q: "What does IEEE 802.3 data encapsulation include? (Choose two.)",
  o: ["Source and destination MAC addresses", "A frame check sequence (FCS) trailer", "Source and destination IP addresses", "TCP port numbers", "A TTL field"], a: [0, 1],
  e: "Инкапсуляция 802.3: структура кадра, Ethernet addressing (MAC) и error detection (FCS trailer)." },
{ l: "4", q: "Why do modern Ethernet LANs not require CSMA/CD?",
  o: ["Switches operate in full-duplex", "Hubs prevent collisions", "Ethernet uses token passing", "Frames are encrypted"],
  e: "Full-duplex на коммутаторах убирает коллизии; CSMA/CD нужен только на общей half-duplex среде (шина, хабы)." },
{ l: "4", q: "Which WAN topology is the simplest and most common, consisting of a permanent link between two endpoints?",
  o: ["Point-to-point", "Hub and spoke", "Mesh", "Ring"],
  e: "Point-to-point — постоянная связь двух узлов, протоколы очень простые." },
{ l: "4", q: "Which WAN topology provides high availability but requires every end system to be connected to every other?",
  o: ["Mesh", "Hub and spoke", "Point-to-point", "Bus"],
  e: "Mesh — каждый с каждым. Hub and spoke — центральный узел и филиалы." },
{ l: "4", q: "Which LAN topology is typically used today because it is easy to install, scalable and easy to troubleshoot?",
  o: ["Star or extended star", "Bus", "Ring", "Full mesh"],
  e: "Star / extended star. Bus и ring — legacy (ранний Ethernet, Token Ring)." },
{ l: "4", q: "Which communication mode allows both devices to transmit and receive simultaneously?",
  o: ["Full-duplex", "Half-duplex", "Simplex", "Contention-based"],
  e: "Full-duplex — одновременно; half-duplex — по очереди (WLAN, хабы)." },
{ l: "4", q: "Which access method is used by IEEE 802.11 WLANs?",
  o: ["CSMA/CA", "CSMA/CD", "Token passing", "Controlled access"],
  e: "CSMA/CA (collision avoidance) — Wi-Fi. CSMA/CD (collision detection) — legacy Ethernet." },
{ l: "4", q: "In CSMA/CD, what do devices do after detecting a collision?",
  o: ["Wait a random period of time and retransmit", "Immediately retransmit", "Send the duration of the transmission", "Pass a token"],
  e: "Обнаружив коллизию, устройства ждут случайное время и повторяют передачу." },
{ l: "4", q: "In CSMA/CA, how do devices avoid collisions?",
  o: ["The transmitting device includes the time duration needed for the transmission", "Devices wait for a token", "Devices detect collisions and retransmit", "Only one device is allowed on the network"],
  e: "Передающий объявляет длительность передачи, остальные знают, сколько среда будет занята." },
{ l: "4", q: "Which access method is deterministic, giving each node its own time on the medium?",
  o: ["Controlled access", "CSMA/CD", "CSMA/CA", "Contention-based access"],
  e: "Controlled access (Token Ring, ARCNET). CSMA — contention-based." },
{ l: "4", q: "What are the three parts of a data link frame?",
  o: ["Header, data, trailer", "Preamble, data, FCS only", "Segment, packet, frame", "Source, destination, TTL"],
  e: "Кадр = header + data + trailer; поля header и trailer зависят от протокола." },
{ l: "4", q: "Which frame field identifies the encapsulated Layer 3 protocol?",
  o: ["Type", "Control", "Addressing", "Error detection"],
  e: "Type — какой протокол L3 внутри; control — flow control; addressing — source и destination." },
{ l: "4", q: "Which statement is true about Layer 2 addresses?",
  o: ["They are used only for local delivery and are updated by each device that forwards the frame", "They stay the same from source to final destination", "They are 32-bit logical addresses", "They are contained in the IP header"],
  e: "L2 (physical) адрес — в заголовке кадра, только для доставки по линку, переписывается на каждом хопе." },
{ l: "4", q: "Which two are WAN data link protocols? (Choose two.)",
  o: ["PPP", "HDLC", "Ethernet", "802.11", "Bluetooth"], a: [0, 1],
  e: "WAN: PPP, HDLC, Frame Relay. LAN: Ethernet, 802.11." },
{ l: "4", q: "What is the minimum size of an Ethernet frame?",
  o: ["64 bytes", "46 bytes", "1518 bytes", "8 bytes"],
  e: "Минимум 64 байта, максимум 1518 (preamble не считается). 46 — минимум поля data." },
{ l: "4", q: "What is the maximum size of a standard Ethernet frame (not including the preamble)?",
  o: ["1518 bytes", "1500 bytes", "1526 bytes", "9000 bytes"],
  e: "1518 = 6 + 6 + 2 + 1500 + 4. 1500 — максимум данных (MTU)." },
{ l: "4", q: "What happens to an Ethernet frame that is less than 64 bytes long?",
  o: ["It is considered a runt frame and is automatically discarded", "It is padded and forwarded", "It is treated as a jumbo frame", "It is sent to the default gateway"],
  e: "Кадр меньше 64 байт — collision fragment / runt, отбрасывается автоматически." },
{ l: "4", q: "A frame contains more than 1500 bytes of data. What is it called?",
  o: ["Jumbo or baby giant frame", "Runt frame", "Collision fragment", "Broadcast frame"],
  e: "Больше 1500 байт данных — jumbo / baby giant; поддерживается многими Fast и Gigabit Ethernet устройствами." },
{ l: "4", q: "Which field of the Ethernet frame is used for error detection?",
  o: ["Frame Check Sequence (FCS)", "Preamble", "Type/Length", "Source MAC"],
  e: "FCS (4 байта, CRC) в trailer используется для обнаружения ошибок." },
{ l: "4", q: "How many bits are in an Ethernet MAC address?",
  o: ["48", "32", "64", "128"],
  e: "MAC = 48 бит = 12 hex-цифр = 6 байт. IPv4 — 32 бита, IPv6 — 128." },
{ l: "4", q: "What is the organizationally unique identifier (OUI) in a MAC address?",
  o: ["The first 24 bits (6 hex digits) assigned to the vendor by the IEEE", "The last 24 bits assigned by the vendor", "The first 8 bits that indicate multicast", "The full 48-bit address"],
  e: "OUI — первые 6 hex-цифр (24 бита), выдаёт IEEE; остальные 6 hex назначает производитель." },
{ l: "4", q: "What is the hexadecimal representation of binary `0000 1010`?",
  o: ["`0A`", "`A0`", "`10`", "`0F`"],
  e: "0000 = 0, 1010 = A → 0A. Ведущие нули в hex всегда показывают." },
{ l: "4", q: "What is the decimal value of `0xC9`?",
  o: ["201", "129", "192", "209"],
  e: "C = 12: 12 · 16 + 9 = 201." },
{ l: "4", q: "What does a NIC do when it receives a frame whose destination MAC does not match its own and is not a broadcast or a joined multicast?",
  o: ["It discards the frame", "It forwards the frame out all ports", "It passes the frame up to the network layer", "It sends an ARP request"],
  e: "Нет совпадения → NIC отбрасывает кадр; совпало → деинкапсуляция вверх." },
{ l: "4", q: "What is the destination MAC address of an Ethernet broadcast frame?",
  o: ["`FF-FF-FF-FF-FF-FF`", "`01-00-5E-00-00-01`", "`00-00-00-00-00-00`", "`33-33-00-00-00-01`"],
  e: "Broadcast — все 48 бит единицы: FF-FF-FF-FF-FF-FF. 01-00-5E — IPv4 multicast, 33-33 — IPv6 multicast." },
{ l: "4", q: "A frame has a destination MAC address beginning with `01-00-5E`. What type of frame is it?",
  o: ["IPv4 multicast", "IPv6 multicast", "Broadcast", "Unicast"],
  e: "01-00-5E — IPv4 multicast, 33-33 — IPv6 multicast." },
{ l: "4", q: "Which statement about the source MAC address of a frame is always true?",
  o: ["It is a unicast address", "It can be a broadcast address", "It can be a multicast address", "It is the MAC of the default gateway"],
  e: "Source MAC всегда unicast; broadcast и multicast бывают только адресом назначения." },
{ l: "4", q: "Which process does an IPv4 host use to determine the destination MAC address of a device when it knows its IPv4 address?",
  o: ["ARP", "Neighbor Discovery", "DNS", "DHCP"],
  e: "IPv4 → ARP, IPv6 → Neighbor Discovery (ND)." },
{ l: "4", q: "How does a switch forward a broadcast frame?",
  o: ["Out all ports except the incoming port", "Only to the default gateway", "Out the port listed in the MAC table", "It drops it"],
  e: "Broadcast (и multicast без snooping) — flood во все порты, кроме входящего. Роутер broadcast не пересылает." },
{ l: "4", q: "What does a Layer 2 switch use to make forwarding decisions?",
  o: ["Destination MAC addresses in its MAC address table", "Destination IP addresses", "TCP port numbers", "The TTL value"],
  e: "Коммутатор L2 решает только по MAC и не знает, что в поле data кадра." },
{ l: "4", q: "What is another name for the MAC address table?",
  o: ["CAM table", "ARP table", "Routing table", "NAT table"],
  e: "MAC address table = CAM (content addressable memory) table." },
{ l: "4", q: "Which address does a switch examine to populate its MAC address table?",
  o: ["Source MAC address", "Destination MAC address", "Source IP address", "Destination IP address"],
  e: "Learn — по source MAC и порту входа; forward — по destination MAC." },
{ l: "4", q: "A switch receives a unicast frame whose destination MAC address is not in its MAC table. What does it do?",
  o: ["Floods it out all ports except the incoming port", "Drops the frame", "Sends it back out the incoming port", "Sends an ARP request"],
  e: "Unknown unicast → flood во все порты, кроме входящего." },
{ l: "4", q: "By default, how long do most Ethernet switches keep an entry in the MAC address table?",
  o: ["5 minutes", "30 seconds", "4 hours", "Until the switch reloads"],
  e: "По умолчанию 5 минут; таймер обновляется при каждом кадре от этого MAC." },
{ l: "4", q: "What is the state of the MAC address table when a switch is first powered on?",
  o: ["Empty", "Filled with the MACs of all connected hosts", "Loaded from NVRAM", "Contains only the broadcast address"],
  e: "При включении таблица пустая и заполняется по source MAC входящих кадров." },
{ l: "4", q: "How does a legacy Ethernet hub differ from a switch?",
  o: ["A hub repeats bits out all ports except the incoming port", "A hub uses a MAC address table", "A hub operates in full-duplex", "A hub routes between networks"],
  e: "Хаб повторяет биты во все порты; коммутатор фильтрует по MAC-таблице." },

/* ---------------- L5 ---------------- */
{ l: "5", q: "Which two are basic operations performed by the network layer? (Choose two.)",
  o: ["Addressing end devices", "Routing", "Error correction with retransmission", "Media access control", "Bit encoding"], a: [0, 1],
  e: "Network layer: addressing end devices, encapsulation, routing, de-encapsulation." },
{ l: "5", q: "What does IP encapsulate?",
  o: ["The transport layer segment", "The data link frame", "The application data directly", "The physical bit stream"],
  e: "IP инкапсулирует сегмент транспортного уровня в пакет." },
{ l: "5", q: "Which characteristic of IP means it does not establish a connection with the destination before sending a packet?",
  o: ["Connectionless", "Best effort", "Media independent", "Reliable"],
  e: "Connectionless: нет установки соединения и управляющей информации; если нужно, это делает TCP." },
{ l: "5", q: "What does 'best effort' mean for IP?",
  o: ["IP does not guarantee delivery of the packet", "IP retransmits lost packets", "IP waits for acknowledgments", "IP always chooses the fastest path"],
  e: "Best effort: доставка не гарантируется, нет переотправки и подтверждений, IP не знает, работает ли получатель." },
{ l: "5", q: "Which characteristic means IP can be sent over copper, fiber or wireless?",
  o: ["Media independent", "Connectionless", "Best effort", "Unreliable"],
  e: "IP не зависит от типа кадра L2 и среды L1." },
{ l: "5", q: "Which protocol typically handles connection-oriented, reliable delivery for IP traffic?",
  o: ["TCP", "UDP", "ARP", "ICMP"],
  e: "IP ненадёжен; гарантии даёт TCP на транспортном уровне." },
{ l: "5", q: "When does IPv4 fragmentation occur?",
  o: ["When a router forwards a packet onto a link with a smaller MTU", "When a switch floods a frame", "When TTL reaches zero", "When ARP fails"],
  e: "Например, переход из Ethernet в медленный WAN с меньшим MTU. Фрагментация добавляет latency." },
{ l: "5", q: "Which statement about IPv6 fragmentation is true?",
  o: ["Routers do not fragment IPv6 packets", "Routers always fragment IPv6 packets", "IPv6 uses the Fragment Offset field in the main header", "IPv6 fragments at the data link layer"],
  e: "IPv6 роутеры не фрагментируют; при необходимости фрагментирует источник через extension header." },
{ l: "5", q: "What value does the 4-bit Version field contain in an IPv4 header?",
  o: ["`0100`", "`0110`", "`0001`", "`1111`"],
  e: "IPv4 = 0100 (4), IPv6 = 0110 (6)." },
{ l: "5", q: "Which IPv4 header field is decremented by each router and causes the packet to be discarded when it reaches zero?",
  o: ["Time to Live (TTL)", "Header Checksum", "Protocol", "Differentiated Services"],
  e: "TTL — счётчик хопов L3. В IPv6 его заменяет Hop Limit." },
{ l: "5", q: "Which IPv4 header field identifies the next-level protocol, such as TCP, UDP or ICMP?",
  o: ["Protocol", "Version", "TTL", "Flags"],
  e: "Protocol (в IPv6 — Next Header)." },
{ l: "5", q: "Which IPv4 header field is used for QoS?",
  o: ["Differentiated Services (DS)", "TTL", "Header Checksum", "Identification"],
  e: "DS (DiffServ, раньше ToS). В IPv6 — Traffic Class." },
{ l: "5", q: "What is the purpose of the IPv4 Header Checksum field?",
  o: ["To detect corruption in the IPv4 header", "To detect corruption in the payload", "To encrypt the header", "To count hops"],
  e: "Header Checksum проверяет только заголовок; в IPv6 это поле убрано." },
{ l: "5", q: "How long are the source and destination addresses in an IPv4 header?",
  o: ["32 bits each", "48 bits each", "128 bits each", "16 bits each"],
  e: "IPv4 — 32 бита, IPv6 — 128, MAC — 48." },
{ l: "5", q: "Which two are limitations of IPv4? (Choose two.)",
  o: ["IPv4 address depletion", "Lack of end-to-end connectivity because of NAT", "Header too small to carry a TTL", "No support for routing", "No support for Ethernet"], a: [0, 1],
  e: "Ограничения IPv4: исчерпание адресов, нет end-to-end connectivity (NAT), рост сложности сети." },
{ l: "5", q: "What is an improvement provided by IPv6?",
  o: ["Increased address space based on 128-bit addresses", "A larger header with more fields", "Mandatory NAT", "Support for broadcast"],
  e: "IPv6: 128 бит, упрощённый заголовок, нет нужды в NAT." },
{ l: "5", q: "What is the fixed length of the IPv6 header?",
  o: ["40 bytes", "20 bytes", "60 bytes", "128 bytes"],
  e: "Заголовок IPv6 фиксирован: 40 байт (упрощён, но не меньше IPv4)." },
{ l: "5", q: "Which two IPv4 fields were removed from the IPv6 header? (Choose two.)",
  o: ["Header Checksum", "Fragment Offset", "Source Address", "Version", "Destination Address"], a: [0, 1],
  e: "Убраны Flags, Fragment Offset, Header Checksum (и др.) для производительности." },
{ l: "5", q: "Which IPv6 header field replaces the IPv4 TTL field?",
  o: ["Hop Limit", "Flow Label", "Traffic Class", "Next Header"],
  e: "Hop Limit = TTL; Next Header = Protocol; Traffic Class = DS." },
{ l: "5", q: "Which IPv6 header field informs devices to handle packets with identical labels the same way?",
  o: ["Flow Label", "Traffic Class", "Payload Length", "Hop Limit"],
  e: "Flow Label — 20-битное поле." },
{ l: "5", q: "Where are IPv6 extension headers placed?",
  o: ["Between the IPv6 header and the payload", "Before the IPv6 header", "In the Ethernet trailer", "Inside the TCP header"],
  e: "Extension headers — необязательные, между заголовком IPv6 и payload (фрагментация, безопасность, мобильность)." },
{ l: "5", q: "Which address does an IPv4 host use to send packets to itself?",
  o: ["`127.0.0.1`", "`0.0.0.0`", "`255.255.255.255`", "`169.254.0.1`"],
  e: "Loopback: 127.0.0.1 в IPv4, ::1 в IPv6." },
{ l: "5", q: "How does an IPv4 host determine whether a destination is local or remote?",
  o: ["It compares its own IP address and subnet mask with the destination IP address", "It sends an ARP request to every host", "It checks the destination MAC address", "It asks the default gateway"],
  e: "IPv4 — по своему IP, маске и IP получателя; IPv6 — по префиксу от локального роутера." },
{ l: "5", q: "Where does a host send traffic destined for a remote network?",
  o: ["To the default gateway", "Directly to the remote host's MAC", "To the DNS server", "Out all ports"],
  e: "Удалённый трафик идёт на default gateway в LAN." },
{ l: "5", q: "A host has no default gateway configured. What is the result?",
  o: ["It can communicate on the local network but not with remote networks", "It cannot communicate at all", "It can reach remote networks but not local hosts", "It will use the DNS server as a gateway"],
  e: "Без шлюза (или с неверным) трафик не выйдет из LAN; внутри LAN связь работает." },
{ l: "5", q: "Which statement is true about a default gateway?",
  o: ["It must have an IP address in the same range as the rest of the LAN", "It must be a Layer 2 switch", "It must be on a remote network", "It is needed for local communication"],
  e: "Шлюз — роутер или L3-коммутатор в том же диапазоне адресов, что и LAN." },
{ l: "5", q: "Which two Windows commands display the host routing table? (Choose two.)",
  o: ["`route print`", "`netstat -r`", "`ipconfig /all`", "`arp -a`", "`tracert`"], a: [0, 1],
  e: "`route print` и `netstat -r`: Interface List, IPv4 Route Table, IPv6 Route Table." },
{ l: "5", q: "Which type of route is added automatically to a router's routing table when an interface is active and has an address?",
  o: ["Directly connected", "Static", "Dynamic", "Default"],
  e: "Directly connected добавляются автоматически; remote — static или dynamic; default — когда нет совпадения." },
{ l: "5", q: "What is a characteristic of static routing?",
  o: ["It must be adjusted manually when the topology changes", "It automatically discovers remote networks", "It finds new best paths after a failure", "It is best for large redundant networks"],
  e: "Static: вручную, правится вручную, для маленьких сетей без резервирования; часто для default route." },
{ l: "5", q: "What can dynamic routing protocols do automatically? (Choose two.)",
  o: ["Discover remote networks", "Find new best paths when the topology changes", "Assign MAC addresses", "Encrypt all traffic", "Replace the need for IP addresses"], a: [0, 1],
  e: "Dynamic routing: находит сети, поддерживает актуальность, выбирает лучший путь, ищет новый при изменениях." },
{ l: "5", q: "In the output of `show ip route`, what does the code `L` indicate?",
  o: ["A directly connected local interface IP address", "A directly connected network", "A static route", "An OSPF route"],
  e: "L — адрес самого интерфейса (/32); C — подключённая сеть; S — static; O — OSPF; D — EIGRP." },
{ l: "5", q: "In `show ip route`, how is a static default route marked?",
  o: ["`S*`", "`C`", "`L`", "`D`"],
  e: "S* — static default route (gateway of last resort)." },
{ l: "5", q: "A host sends a packet to a host on a remote network. Which destination MAC address is in the frame?",
  o: ["The MAC address of the default gateway", "The MAC address of the remote host", "The broadcast MAC address", "The MAC address of the DNS server"],
  e: "Remote → dst MAC шлюза, dst IP конечного хоста. Local → dst MAC самого получателя." },
{ l: "5", q: "A host sends a packet to a host on the same network. Which destination addresses are used?",
  o: ["The destination host's IP address and MAC address", "The default gateway's IP and MAC address", "The destination host's IP and the gateway's MAC", "The broadcast IP and MAC"],
  e: "В той же сети и IP, и MAC — самого получателя." },
{ l: "5", q: "What are the two basic functions of ARP? (Choose two.)",
  o: ["Resolving IPv4 addresses to MAC addresses", "Maintaining a table of IPv4-to-MAC mappings", "Resolving domain names to IP addresses", "Assigning IP addresses to hosts", "Routing packets between networks"], a: [0, 1],
  e: "ARP: resolve IPv4 → MAC и вести ARP table." },
{ l: "5", q: "A host wants to send a packet to a remote network. Which IPv4 address does it look for in its ARP table?",
  o: ["The IPv4 address of the default gateway", "The IPv4 address of the remote host", "Its own IPv4 address", "The broadcast address"],
  e: "Для удалённой сети ищется IP шлюза, потому что кадр пойдёт на MAC шлюза." },
{ l: "5", q: "What does a device do if there is no entry in its ARP table for the needed IPv4 address?",
  o: ["It sends an ARP request", "It drops the packet", "It sends the packet to the DNS server", "It uses the broadcast MAC as destination for the data"],
  e: "Отправляется ARP request (broadcast), владелец отвечает ARP reply (unicast)." },
{ l: "5", q: "Which protocol is used by IPv6 to associate an IPv6 address with a MAC address?",
  o: ["ICMPv6 (Neighbor Discovery)", "ARP", "DHCPv6", "DNS"],
  e: "IPv6 использует ICMPv6 Neighbor Discovery вместо ARP." },
{ l: "5", q: "Which command activates a router interface?",
  o: ["`no shutdown`", "`ip address`", "`enable`", "`interface up`"],
  e: "Интерфейсы роутера по умолчанию выключены; `no shutdown` активирует." },
{ l: "5", q: "Which command is good practice to add information about the network connected to an interface?",
  o: ["`description`", "`banner motd`", "`hostname`", "`remark`"],
  e: "`description Link to LAN` в interface config." },
{ l: "5", q: "Which command assigns an IPv4 address to a router interface?",
  o: ["`ip address 192.168.10.1 255.255.255.0`", "`ip address 192.168.10.1/24`", "`ipv4 192.168.10.1`", "`ip default-gateway 192.168.10.1`"],
  e: "IPv4 — адрес и маска через пробел; IPv6 — `ipv6 address 2001:db8:acad:10::1/64`." },
{ l: "5", q: "Which command displays all interfaces, their IP addresses and their current status in a brief table?",
  o: ["`show ip interface brief`", "`show running-config`", "`show interfaces`", "`show ip route`"],
  e: "`show ip interface brief` (и `show ipv6 interface brief`)." },
{ l: "5", q: "Which command displays statistics for all interfaces, including runts and giants?",
  o: ["`show interfaces`", "`show ip interface brief`", "`show ip route`", "`show ipv6 route`"],
  e: "`show interfaces` — подробная статистика; из адресов показывает только IPv4." },
{ l: "5", q: "Which command configures a default gateway on a Layer 2 switch?",
  o: ["`ip default-gateway 192.168.10.1`", "`ip route 0.0.0.0 0.0.0.0 192.168.10.1`", "`default-gateway 192.168.10.1` in interface mode", "`gateway 192.168.10.1`"],
  e: "`ip default-gateway` в global config." },
{ l: "5", q: "Why does a Layer 2 switch need a default gateway?",
  o: ["To be managed remotely from another network", "To forward hosts' traffic between VLANs", "To learn MAC addresses", "To build its routing table"],
  e: "Шлюз коммутатору нужен только для его собственного management-трафика из других сетей." },
{ l: "5", q: "Which command on a router restricts VTY access to SSH and Telnet?",
  o: ["`transport input ssh telnet`", "`login local`", "`line vty 0 4`", "`service password-encryption`"],
  e: "`transport input {ssh | telnet}` в line vty указывает разрешённые протоколы." }
];
